const colors = require('tailwindcss/colors')

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js}"],
  darkMode: 'class',
  theme: {
    colors:{
      'l-pri': '#7045BA',
      'l-on-pri': '#FFFFFF',
      'l-pri-c': '#EBDCFF',
      'l-on-pri-c': '#260059',
      'l-sec': '#645A76',
      'l-on-sec': '#FFFFFF',
      'l-sec-c': '#EBDDFE',
      'l-on-sec-c': '#20172F',
      'l-ter': '#864E5D',
      'l-on-ter': '#FFFFFF',
      'l-ter-c': '#FFD9E1',
      'l-on-ter-c': '#360C1B',
      'l-error': '#BA1A1A',
      'l-on-error': '#FFFFFF',
      'l-error-c': '#FFDAD6',
      'l-on-error-c': '#410002',
      'l-bg': '#FFFBFF',
      'l-on-bg': '#1D1B1E',
      'l-surface': '#FFFBFF',
      'l-on-surface': '#1D1B1E',
      'l-surface-var': '#E7E0EB',
      'l-on-surface-var': '#49454E',
      'l-outline': '#7A757F',

      'd-pri': '#D4BBFF',
      'd-on-pri': '#40048A',
      'd-pri-c': '#572AA1',
      'd-on-pri-c': '#EBDCFF',
      'd-sec': '#CEC1E2',
      'd-on-sec': '#352C46',
      'd-sec-c': '#4C425D',
      'd-on-sec-c': '#EBDDFE',
      'd-ter': '#FBB3C4 ',
      'd-on-ter': '#50212F',
      'd-ter-c': '#6B3745',
      'd-on-ter-c': '#FFD9E1',
      'd-error': '#FFB4AB',
      'd-on-error': '#690005',
      'd-error-c': '#93000A',
      'd-on-error-c': '#FFB4AB',
      'd-bg': '#1D1B1E',
      'd-on-bg': '#E6E1E6',
      'd-surface': '#1D1B1E',
      'd-on-surface': '#E6E1E6',
      'd-surface-var': '#49454E',
      'd-on-surface-var': '#CBC4CF',
      'd-outline': '#948F99',
    },
    extend: {
      colors,
      fontFamily:{
        Roboto: ['Roboto'],
        Poppins: ['Poppins'],
      }
    },
  },
  plugins: [],
}
